#include<stdio.h>
main()
{
    int d,d2,m,m2,y,y2,count=0;
    scanf("%d %d %d",&d,&m,&y);
    scanf("%d %d %d",&d2,&m2,&y2);
    while(d!=d2 || m!=m2 || y!=y2)
    {
        if(y%4==0)
        {
            if(m==1)
            {
                if(d==31)
                {
                    d=0;
                    m++;
                }
            }
            if(m==2)
            {
                if(d==29)
                {
                    d=0;
                    m++;
                }
            }
            if(m==3)
            {
                if(d==31)
                {
                    d=0;
                    m++;
                }
            }
            if(m==4)
            {
                if(d==30)
                {
                    d=0;
                    m++;
                }
            }
            if(m==5)
            {
                if(d==31)
                {
                    d=0;
                    m++;
                }
            }
            if(m==6)
            {
                if(d==30)
                {
                    d=0;
                    m++;
                }
            }
            if(m==7)
            {
                if(d==31)
                {
                    d=0;
                    m++;
                }
            }
            if(m==8)
            {
                if(d==31)
                {
                    d=0;
                    m++;
                }
            }
            if(m==9)
            {
                if(d==30)
                {
                    d=0;
                    m++;
                }
            }
            if(m==10)
            {
                if(d==31)
                {
                    d=0;
                    m++;
                }
            }
            if(m==11)
            {
                if(d==30)
                {
                    d=0;
                    m++;
                }
            }
            if(m==12)
            {
                if(d==31)
                {
                    d=0;
                    m=1;
                    y++;
                }
            }

        }
        else
        {
            if(m==1)
            {
                if(d==31)
                {
                    d=0;
                    m++;
                }
            }
            if(m==2)
            {
                if(d==28)
                {
                    d=0;
                    m++;
                }
            }
            if(m==3)
            {
                if(d==31)
                {
                    d=0;
                    m++;
                }
            }
            if(m==4)
            {
                if(d==30)
                {
                    d=0;
                    m++;
                }
            }
            if(m==5)
            {
                if(d==31)
                {
                    d=0;
                    m++;
                }
            }
            if(m==6)
            {
                if(d==30)
                {
                    d=0;
                    m++;
                }
            }
            if(m==7)
            {
                if(d==31)
                {
                    d=0;
                    m++;
                }
            }
            if(m==8)
            {
                if(d==31)
                {
                    d=0;
                    m++;
                }
            }
            if(m==9)
            {
                if(d==30)
                {
                    d=0;
                    m++;
                }
            }
            if(m==10)
            {
                if(d==31)
                {
                    d=0;
                    m++;
                }
            }
            if(m==11)
            {
                if(d==30)
                {
                    d=0;
                    m++;
                }
            }
            if(m==12)
            {
                if(d==31)
                {
                    d=0;
                    m=1;
                    y++;
                }
            }
        }
        d++;
        count++;
    }
    printf("%d",count);
}
